version: '3'

#no docker-compose adicionamos os serviços que serão usados no projeto
services:
#banco de dados
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
#gerenciador das mensagens e stream de dados no kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#kafka é um serviço de mensageria e stream de dados
  kafka:
    image: confluentinc/cp-server:7.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROCOL_MAP: 







 # rabbitmq:
 # image: rabbitmq:3-management
 # container_name: rabbitmq
 # restart: always
 # ports: 
  #  - 5672:5672
  #  - 15672:15672
